// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nndzggplxnxvczknkdjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZHpnZ3BseG54dmN6a25rZGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTY4MzksImV4cCI6MjA3NTc5MjgzOX0.zMOavAJ61Vs0C4AyeKD4e1xeyAOHjPvIhn-mXajs5jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});