// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksdvxfbrhtnrcuqmwzkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZHZ4ZmJyaHRucmN1cW13emtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTk3MDMsImV4cCI6MjA3ODAzNTcwM30.hqLVBNVOFII6n0di78-bSzDv-PWukGEU9Usqh50EHJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});